name: 'Get & cache dependencies.'
description: 'Get the dependencies (by npm) and cache them.'
inputs:
  caching:
    description: 'Whether caching need to be used or not'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} 
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.cacging != 'true'
      run: npm ci
      shell: bash